In [2]:
import util as u
import tensorflow as tf
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten
from keras import backend as K
from keras import optimizers
from keras import metrics

In [3]:
xs,ys = u.get_dataset()

In [11]:
def relu_advanced(x):
    return K.relu(x, max_value=512)

#create model
model = Sequential()
#add model layers
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(512, 512, 3)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
#model.add(Conv2D(128, kernel_size=5, activation='relu'))
#model.add(Conv2D(256, kernel_size=7, activation='relu'))
#model.add(Conv2D(256, kernel_size=9, activation='relu'))
model.add(Flatten())
model.add(Dense(4, activation = 'sigmoid'))

# https://towardsdatascience.com/building-a-convolutional-neural-network-cnn-in-keras-329fbbadc5f5

In [12]:
#compile model using accuracy to measure model performance
model.compile(loss='mean_squared_error', optimizer='Adam',  metrics=['acc'])

In [13]:
X_train  = xs[:30]
y_train = ys[:30]/512; y_train = y_train.reshape(30,4)
X_test = xs[30:39]
y_test = ys[30:39]/512; y_test = y_test.reshape(9,4)

In [14]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size= 1, epochs= 2)

Train on 30 samples, validate on 9 samples
Epoch 1/2
30/30 [==============================] - 29s 961ms/step - loss: 0.3111 - acc: 0.0000e+00 - val_loss: 0.3641 - val_acc: 0.0000e+00
Epoch 2/2
30/30 [==============================] - 30s 993ms/step - loss: 0.3145 - acc: 0.0000e+00 - val_loss: 0.3641 - val_acc: 0.0000e+00


In [17]:
model.predict(X_test[:4])


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [18]:
print(y_test[:4])

[[0.265625   0.37304688 0.31835938 0.43945312]
 [0.265625   0.54492188 0.31640625 0.59179688]
 [0.26757812 0.375      0.3203125  0.4375    ]
 [0.31835938 0.43164062 0.3671875  0.49023438]]
