In [18]:
import util as u
import tensorflow as tf
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten

In [19]:
xs,ys = u.get_dataset()

In [20]:
x_train = xs[:30]
y_train = ys[:30]
x_test = xs[30:39]
y_test = ys[30:39]

In [4]:
#tf tut from tf homepage
# https://www.tensorflow.org/overview/

'''
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)
'''

"\nimport tensorflow as tf\nmnist = tf.keras.datasets.mnist\n\n(x_train, y_train),(x_test, y_test) = mnist.load_data()\nx_train, x_test = x_train / 255.0, x_test / 255.0\n\nmodel = tf.keras.models.Sequential([\n  tf.keras.layers.Flatten(input_shape=(28, 28)),\n  tf.keras.layers.Dense(128, activation='relu'),\n  tf.keras.layers.Dropout(0.2),\n  tf.keras.layers.Dense(10, activation='softmax')\n])\n\nmodel.compile(optimizer='adam',\n              loss='sparse_categorical_crossentropy',\n              metrics=['accuracy'])\n\nmodel.fit(x_train, y_train, epochs=5)\nmodel.evaluate(x_test, y_test)\n"

In [21]:
from keras import backend as K

def relu_advanced(x):
    return K.relu(x, max_value=512)

#create model
model = Sequential()
#add model layers
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(512, 512, 3)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
model.add(Flatten())
model.add(Dense(4, activation = None))

# https://towardsdatascience.com/building-a-convolutional-neural-network-cnn-in-keras-329fbbadc5f5

In [22]:
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='hinge', metrics=['accuracy'])

In [23]:
X_train  = xs[:30]
y_train = ys[:30]; y_train = y_train.reshape(30,4)
X_test = xs[30:39]
y_test = ys[30:39]; y_test = y_test.reshape(9,4)

In [24]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs= 10)

Train on 30 samples, validate on 9 samples
Epoch 1/10
30/30 [==============================] - 17s 568ms/step - loss: 752.8152 - accuracy: 0.5000 - val_loss: 0.0000e+00 - val_accuracy: 0.1111
Epoch 2/10
30/30 [==============================] - 14s 456ms/step - loss: 0.0000e+00 - accuracy: 0.2333 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 3/10
30/30 [==============================] - 15s 487ms/step - loss: 1.9694 - accuracy: 0.2000 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 4/10
30/30 [==============================] - 15s 511ms/step - loss: 0.0000e+00 - accuracy: 0.0333 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 5/10
30/30 [==============================] - 15s 489ms/step - loss: 0.0000e+00 - accuracy: 0.0333 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 6/10
30/30 [==============================] - 14s 470ms/step - loss: 0.0000e+00 - accuracy: 0.0333 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 7/10
30/30 [===================

In [15]:
model.predict(X_test[:4])


array([[-1326.7125, -1318.61  , -1320.7202, -1315.0171],
       [-1261.9913, -1252.6326, -1254.1976, -1246.141 ],
       [-1240.8658, -1232.4849, -1235.8159, -1226.8784],
       [-1253.7181, -1247.0774, -1247.4739, -1241.4811]], dtype=float32)

In [16]:
print(y_test[:4])

[[136. 191. 163. 225.]
 [136. 279. 162. 303.]
 [137. 192. 164. 224.]
 [163. 221. 188. 251.]]


In [ ]:
#From Coursera
import numpy as np
from keras import layers
from keras.layers import Input, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D
from keras.layers import AveragePooling2D, MaxPooling2D, Dropout, GlobalMaxPooling2D, GlobalAveragePooling2D
from keras.models import Model
from keras.preprocessing import image
from keras.utils import layer_utils
from keras.utils.data_utils import get_file
from keras.applications.imagenet_utils import preprocess_input
import pydot
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
from kt_utils import *

import keras.backend as K
K.set_image_data_format('channels_last')
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow

%matplotlib inline