In [3]:
import util as u
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten

In [6]:
xs,ys = u.get_dataset()

In [8]:
#create model
model = Sequential()
#add model layers
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(512, 512, 3)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
model.add(Flatten())
model.add(Dense(4, activation = 'sigmoid'))

# https://towardsdatascience.com/building-a-convolutional-neural-network-cnn-in-keras-329fbbadc5f5

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [9]:
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

In [10]:
X_train  = xs[:30]
y_train = ys[:30]; y_train = y_train.reshape(30,4)/512
X_test = xs[30:39]
y_test = ys[30:39]; y_test = y_test.reshape(9,4)/512

In [14]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size = 1, epochs= 10)

Train on 30 samples, validate on 9 samples
Epoch 1/10
30/30 [==============================] - 42s 1s/sample - loss: 0.2251 - acc: 0.5000 - val_loss: 0.2601 - val_acc: 0.0000e+00
Epoch 2/10
30/30 [==============================] - 48s 2s/sample - loss: 0.2251 - acc: 0.5000 - val_loss: 0.2601 - val_acc: 0.0000e+00
Epoch 3/10
30/30 [==============================] - 45s 1s/sample - loss: 0.2251 - acc: 0.5000 - val_loss: 0.2601 - val_acc: 0.0000e+00
Epoch 4/10
30/30 [==============================] - 42s 1s/sample - loss: 0.2251 - acc: 0.5000 - val_loss: 0.2601 - val_acc: 0.0000e+00
Epoch 5/10
30/30 [==============================] - 42s 1s/sample - loss: 0.2251 - acc: 0.5000 - val_loss: 0.2601 - val_acc: 0.0000e+00
Epoch 6/10
30/30 [==============================] - 46s 2s/sample - loss: 0.2251 - acc: 0.5000 - val_loss: 0.2601 - val_acc: 0.0000e+00
Epoch 7/10
30/30 [==============================] - 44s 1s/sample - loss: 0.2251 - acc: 0.5000 - val_loss: 0.2601 - val_acc: 0.0000e+00
Epoch

In [14]:
model.predict(X_test[:4])


[[136. 191. 163. 225.]
 [136. 279. 162. 303.]
 [137. 192. 164. 224.]
 [163. 221. 188. 251.]]
